name: Check issue title action mitigated
description: Check if the issue title begins with octocat
inputs:
  issue-title:
    description: 'The issue title'
    required: true
runs:
  using: composite
  steps:
    - name: Check issue title
      shell: bash
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
      run: |
        if [[ "$ISSUE_TITLE" =~ ^octocat ]]; then
          echo "Issue title starts with 'octocat'"
          exit 0
          else
          echo "Issue title did not start with 'octocat'"
          exit 1
        fi